#!/bin/bash

# Delay before starting
delay=3
duration=${1:-10}
save_as=${2:-$HOME/recorded.gif}

notify() {
    message=${1:-''}

    printf "%s\n" "$message"
    paplay /usr/share/sounds/KDE-Im-Irc-Event.ogg &
}

# xrectsel from https://github.com/lolilolicon/xrectsel
select_area() {
  local region

  region=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

  echo $region
}

countdown() {
  local delay=$1

  printf "Start recording in: "
  for (( i=$delay; i>0; --i )) ; do
      printf "%s\b" "$i"
      sleep 1
  done
  printf "\n"
}

progress-bar() {
  local duration=${1}


    already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇"; done }
    remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf " "; done }
    percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
    clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 1
      clean_line
  done
  printf "\n"
}



run() {
  printf "Recording for %ss\nsaving in %s\n" "$duration" "$save_as"
  printf "Select Area to record…\n"

  seletected_area="$(select_area)"
  notify "Start…"
  countdown $delay

  progress-bar $duration &
  byzanz-record --verbose --delay=0 ${seletected_area} --duration=$duration $save_as > /dev/null

  notify "Finished!"
}

run
